{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  {{ .Values.secret.discordTokenKey }}: {{ if .Values.env.provideToken }}{{ .Values.env.discordToken }}{{ else }}"REPLACE_WITH_DISCORD_TOKEN"{{ end }}
{{- end }}
